inherit_from: .rubocop.relaxed.yml
require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7

  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Metrics/BlockLength:
  Enabled: false

Rails:
  Enabled: true

Style:
  Documentation:
    Enabled: false

  IndentationConsistency:
    Enabled: true
    EnforcedStyle: rails

  PreferredDelimiters:
    Enabled: false

  ClassAndModuleChildren:
    Enabled: false

  SymbolArray:
    Enabled: false

  StringLiterals:
    EnforcedStyle: double_quotes
    Exclude:
      - './*_helper.rb'

  HashEachMethods:
    Enabled: true

  HashTransformKeys:
    Enabled: true

  HashTransformValues:
    Enabled: true

Layout:
  LineLength:
    Max: 100

  ParameterAlignment:
    EnforcedStyle: with_fixed_indentation
